# Generated by Django 4.2.1 on 2023-06-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yourmodel",
            name="form_format",
            field=models.CharField(default="no_value", max_length=100),
        ),
        migrations.AlterField(
            model_name="yourmodel",
            name="digit_field",
            field=models.IntegerField(
                choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
        migrations.AlterField(
            model_name="yourmodel",
            name="form_value",
            field=models.CharField(default="value", max_length=100),
        ),
    ]
