# Generated by Django 4.2.1 on 2023-06-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_yourmodel_form_format_alter_yourmodel_digit_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yourmodel",
            name="form_format",
        ),
        migrations.RemoveField(
            model_name="yourmodel",
            name="string_field",
        ),
    ]
