# Generated by Django 4.2.1 on 2023-06-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_remove_yourmodel_form_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yourmodel",
            name="image",
            field=models.ImageField(default=2, upload_to="images/"),
            preserve_default=False,
        ),
    ]
