# Generated by Django 4.1.3 on 2023-06-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_yourmodel_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YourModel",
            new_name="ValueModel",
        ),
    ]
