# Generated by Django 4.1.3 on 2023-06-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0005_rename_yourmodel_valuemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_username", models.CharField(default="username", max_length=24)),
                ("form_password", models.CharField(default="password", max_length=24)),
                (
                    "form_confirm_password",
                    models.CharField(default="confirm_password", max_length=24),
                ),
            ],
        ),
    ]
