# Generated by Django 4.2.1 on 2023-08-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_novaluemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuemodel",
            name="catchphrase",
            field=models.CharField(default=" catchphrase", max_length=200),
        ),
        migrations.AddField(
            model_name="valuemodel",
            name="interests",
            field=models.CharField(default="interests", max_length=200),
        ),
        migrations.AddField(
            model_name="valuemodel",
            name="value_importance",
            field=models.CharField(default=" value_importance", max_length=200),
        ),
        migrations.AlterField(
            model_name="valuemodel",
            name="digit_field",
            field=models.IntegerField(choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3")]),
        ),
    ]
