# Generated by Django 4.2.1 on 2023-08-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_valuemodel_catchphrase_valuemodel_interests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="novaluemodel",
            name="catchphrase",
            field=models.CharField(default=" catchphrase", max_length=200),
        ),
        migrations.AddField(
            model_name="novaluemodel",
            name="format",
            field=models.CharField(default=" format", max_length=200),
        ),
        migrations.AddField(
            model_name="novaluemodel",
            name="interests",
            field=models.CharField(default="interests", max_length=200),
        ),
        migrations.AlterField(
            model_name="valuemodel",
            name="digit_field",
            field=models.IntegerField(
                choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
