# Generated by Django 4.1.3 on 2023-08-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_wordleentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="novaluemodel",
            old_name="format",
            new_name="format_importance",
        ),
    ]
