# Generated by Django 4.2.1 on 2023-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0012_rename_format_novaluemodel_format_importance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novaluemodel",
            name="digit_field",
            field=models.IntegerField(choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3")]),
        ),
        migrations.AlterField(
            model_name="valuemodel",
            name="digit_field",
            field=models.IntegerField(choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3")]),
        ),
    ]
