# Generated by Django 4.2.1 on 2023-08-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0013_alter_novaluemodel_digit_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valuemodel",
            name="image",
        ),
    ]
