# Generated by Django 4.2.1 on 2023-08-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0014_remove_valuemodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="novaluemodel",
            name="signup",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.signupmodel",
            ),
        ),
        migrations.AddField(
            model_name="valuemodel",
            name="signup",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.signupmodel",
            ),
        ),
        migrations.AddField(
            model_name="wordleentry",
            name="signup",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.signupmodel",
            ),
        ),
    ]
