# Generated by Django 4.2.1 on 2023-08-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0015_novaluemodel_signup_valuemodel_signup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordleentry",
            name="value",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.valuemodel",
            ),
        ),
    ]
