# Generated by Django 4.2.6 on 2023-10-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0018_post_date_time_alter_post_user_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="value_importance",
        ),
    ]
