# Generated by Django 4.2.6 on 2023-10-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0020_delete_wordleentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="value",
            field=models.CharField(default="your_default_value_here", max_length=20000),
        ),
        migrations.CreateModel(
            name="WordleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter_1", models.CharField(max_length=1)),
                ("letter_2", models.CharField(max_length=1)),
                ("letter_3", models.CharField(max_length=1)),
                ("letter_4", models.CharField(max_length=1)),
                ("letter_5", models.CharField(max_length=1)),
                ("image_data", models.TextField()),
                (
                    "signup",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.signupmodel",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.valuemodel",
                    ),
                ),
            ],
        ),
    ]
