# Generated by Django 4.1.3 on 2023-10-27 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0022_signupmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupmodel",
            name="action_performed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="signupmodel",
            name="registration_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
